Robi_App/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Robi_App.Models;

namespace Robi_App.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult Error (int statusCode)
        {
            Response.StatusCode = statusCode;   
            return View();
        }
    }
}

Robi_App/Controllers/InvoiceController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Robi_App.Models.ViewModels;
using Robi_App.Services;
using System.Security.AccessControl;
using System.Security.Claims;
using System.Threading.Tasks;
using static System.Net.Mime.MediaTypeNames;

namespace Robi_App.Controllers
{

    public class InvoiceController : Controller
    {
        private readonly IStoreService _storeService; 
        private readonly IInvoiceService _invoiceService;
        private readonly IAuthorizationService _authorizationService;

        public InvoiceController(IStoreService storeService, IInvoiceService invoiceService, IAuthorizationService authorizationService)
        {
            _storeService = storeService;
            _invoiceService = invoiceService;
            _authorizationService = authorizationService;
        }
        // admin
        [Authorize(policy: "AdminOrEmployee")]
        public IActionResult Index(string filter = null!)
        {
            IEnumerable<ShowInvoiceVM> invoices = null!;
            if (filter == SD.zeroPoints)
            {
                invoices = _invoiceService.showInvoices(User, i => i.Points == 0);
                TempData["txt"] = "<b> فواتير لا تحتوي علي نقاط </b>";
            }
            else if (filter ==  SD.hasPoints)
            {
                invoices = _invoiceService.showInvoices(User, i => i.Points != 0);
                TempData["txt"] = "<b> فواتير تحتوي علي نقاط</b>";
            }
            else
            {
                invoices = _invoiceService.showInvoices(User);
                TempData["txt"] = "  <b>جميع الفواتير  </b>";
            }
            return View(invoices);
        }
        [Authorize(policy: "AdminOrEmployee")]

        [HttpPost]
        public async Task<IActionResult> UpdatePoints(ShowInvoiceVM model, string url = null! )
        {
            var invoicefromDB = _invoiceService.GetInvoiceToUpdate(model.Id, true); 
            if (invoicefromDB is null  )
            {
                TempData["Message"] = "This Invoice Not Found !";
                return RedirectToAction("Error", "Home", new
                {
                    statusCode = 404
                });
            }
            var result = await _authorizationService.AuthorizeAsync(User, invoicefromDB, "CanUpdateInvoicePoints"); 
            if (!result.Succeeded)
                return new ForbidResult();

            if (model.Points < 0)
                return RedirectToAction("Index");

            invoicefromDB.Points = model.Points;    
            _invoiceService.Save();
            if (url != null)
                return Redirect(url); 
            //**** 
          return RedirectToAction ("Index" , new { filter  = SD.hasPoints} );  
        }
        // Client 
        [Authorize(policy: SD.Role_Client)]
        public IActionResult Create() 
        {
            CreateUpdateInvoiceVM viewModel = new CreateUpdateInvoiceVM()
            {
                Stores = _storeService.GetStores(false).Select(s => new SelectListItem()
                {
                    Value = s.Id.ToString(),
                    Text = s.Title, 
                }).ToList(),    
            };  
            return View(viewModel);
        }
        [Authorize(policy: SD.Role_Client)]
        [HttpPost]
        public IActionResult Create (CreateUpdateInvoiceVM model)
        {
            if (!User.Identity!.IsAuthenticated)
            {
                TempData["Message"] = "You May Not Allowed To Do This Action !";
                return RedirectToAction("Error", "Home" , new
                {
                    statusCode = 403
                });
            }
            bool isExisting = _invoiceService.IsCodeExisting(model.Code); 
            if (!ModelState.IsValid || isExisting)
            {
                model.Stores = _storeService.GetStores(false).Select(s => new SelectListItem()
                {
                    Value = s.Id.ToString(),
                    Text = s.Title,
                }).ToList();
                if (isExisting)
                    ModelState.AddModelError("Code", "This Invoice Number Is Used Before");
                return View(model);
            }

            model.UserId = User.FindFirst(ClaimTypes.NameIdentifier)!.Value; 
            _invoiceService.CreateInvoice(model);
            // will change it soon to UserInvoices
            return RedirectToAction("index" , "Customer"); 
        }
        [Authorize(policy: SD.Role_Client)]
        public async Task<IActionResult> Update (int Id)
        {
            var invoiceFromDB = _invoiceService.GetInvoiceToUpdate(Id , false);
            // her all users can update we will implement resource-based
            // Authorization
            if (invoiceFromDB is null     )
            {
                TempData["Message"] = 
                    "This Invoice Not Found !";
                return RedirectToAction("Error", "Home" , new 
                {
                    statusCode = 404
                });
            }

            var authResult = await _authorizationService
                .AuthorizeAsync(User, invoiceFromDB, "CanUpdateInvoice");
            if (!authResult.Succeeded)
            {
                return new ForbidResult(); 
            }
            CreateUpdateInvoiceVM viewModel = new CreateUpdateInvoiceVM()
            {
                Id = Id,    
                Code = invoiceFromDB.Code,  
                UserId = invoiceFromDB.UserId ,
                StoreId = invoiceFromDB.StoreId ,
                Stores = _storeService.GetStores(false).Select(s => new SelectListItem()
                {
                    Value = s.Id.ToString(),
                    Text = s.Title,
                }).ToList(),
            };
            return View(viewModel);
        }
        [Authorize(policy: SD.Role_Client)]
        [HttpPost] 
        public async Task<IActionResult> Update (CreateUpdateInvoiceVM model)
        {
            
            var invoiceFromDB = _invoiceService.GetInvoiceToUpdate(model.Id , true);

            if (!ModelState.IsValid || invoiceFromDB is null)
            {
                if (invoiceFromDB is null)
                {
                    TempData["Message"] = "This Invoice Not Found  !";
                    return RedirectToAction("Error", "Home", new
                    {
                        statusCode = 404
                    });
                }
                var authResult = await _authorizationService
               .AuthorizeAsync(User, invoiceFromDB, "CanUpdateInvoice");
                if (!authResult.Succeeded)
                {
                    return new ForbidResult();
                }
                // in every case 
                model.Stores = _storeService.GetStores(false).Select(s => new SelectListItem()
                {
                    Value = s.Id.ToString(),
                    Text = s.Title,
                }).ToList();
                return View(model); 
            }
            if (invoiceFromDB.Code != model.Code)
            {
                bool isExisting = _invoiceService.IsCodeExisting(model.Code);
                if (isExisting)
                {
                    ModelState.AddModelError("Code", "This Invoice Number Is Used Before");
                    model.Stores = _storeService.GetStores(false).Select(s => new SelectListItem()
                    {
                        Value = s.Id.ToString(),
                        Text = s.Title,
                    }).ToList();
                    return View(model);
                }
              
            }
            invoiceFromDB.Code = model.Code;
            invoiceFromDB.StoreId = model.StoreId;
            // to allow admin to see it agene 
            invoiceFromDB.IsReviewed = false;
            _invoiceService.Save();

            return RedirectToAction("Index" , "Customer"); 
        }

    }
}

Robi_App/Controllers/StoreController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Robi_App.Models;
using Robi_App.Services;
using System.Collections.Immutable;

namespace Robi_App.Controllers
{
    [Authorize (policy: SD.Role_Admin)]
    public class StoreController : Controller
    {
        private readonly IStoreService _service;
        private readonly IInvoiceService _invoiceService;

        public StoreController(IStoreService service, IInvoiceService invoiceService)
        {
            _service = service;
            _invoiceService = invoiceService;
        }

        public IActionResult Index()
        {
            var Stores = _service.GetStores(false);
            return View(Stores);
        }

        public IActionResult Add()
        {
            return View();
        }   
        [HttpPost]
        public IActionResult Add (Store store )
        {
             if(!ModelState.IsValid)
                return View(store);     
            if (store.Id != 0)
            {
                TempData["Message"] = "Some Error With Data !";
                return RedirectToAction("Error", "Home" , new
                {
                    statusCode = 400
                });
            }
            _service.AddStore(store);   
            return RedirectToAction("Index");
        }

        public IActionResult Update (int id )
        {
            var store = _service.GetStoreById(id , false);
            if (store is null)
            {
                TempData["Message"] = "Sorry ! This Store Not Found";
                return RedirectToAction("Error", "Home", new
                {
                    statusCode = 404
                });
            }

            return View(store); 
        }
        [HttpPost]
        public IActionResult Update (Store store )
        {
            if (!ModelState.IsValid )
               return View(store);  
            
            if ( !_service.StoreExists(store.Id))
            {
                TempData["Message"] = "Sorry ! This Store Not Found";
                return RedirectToAction("Error", "Home" ,  new
                {
                    statusCode = 404
                });
            }
            _service.UpdateStore(store);    
            return RedirectToAction("Index");   
        }

        public IActionResult Delete (int id)
        {
            var store = _service.GetStoreById(id, false);
            if (store is null)
            {
                TempData["Message"] = "Sorry ! This Store Not Found";
                return RedirectToAction("Error", "Home", new
                {
                    statusCode = 404
                });
            }
            return View(store); 
        }

        [HttpPost]
        public IActionResult Delete(Store store)
        {
     
        
            if (!_service.StoreExists(store.Id))
            {
                TempData["Message"] = "Sorry ! This Store Not Found";
                return RedirectToAction("Error", "Home", new
                {
                    statusCode = 404
                });
            }
            _service.DeleteStore(store);
            return RedirectToAction("Index");
        }

        public IActionResult ShowInvoices (int Id)
        {
            var store = _service.ShowStoreInvoicesVM(Id);   
            if (store is null)
            {
                TempData["Message"] = "Sorry ! This Store Not Found";
                return RedirectToAction("Error", "Home" , new {});
            }

            store.Invoices = _invoiceService.showInvoices (null!,  i => i.StoreId == Id);
            return View(store);  
        }
    }
}

Robi_App/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";

}
<div class="container fw-bold mt-4">

    <div class="row align-items-center fw-bold mb-5">
        <div class="col-md-6 text-center text-md-start">
            <h1 class="fw-bold text-primary mb-3">
                <i class="bi bi-stars me-2"></i>
                Point Hub
            </h1>
            <p class="text-muted fs-3 mb-4 text-center">
                نظام شامل لإدارة الفواتير والنقاط للمحلات والفروع
            </p>
            <p class="text-muted fs-4 mb-4 text-center">
                لتسهيل متابعة عملك وزيادة الإنتاجية
            </p>
        </div>

        <div class="col-md-6 text-center">
            <img src="~/icons8-invoice-100.png" class="img-fluid" style="max-width: 350px;">
        </div>
    </div>

    
    <!-- Admin Dashboard -->
   @if (User.HasClaim(c => c.Type == SD.Role_Admin))
    {
        <h4 class="fw-bold text-danger text-center mb-3">
            <i class="bi bi-shield-lock"></i> لوحة تحكم المدير
        </h4>

        <div class="row g-3   justify-content-center ">

            <div class="col-6 col-md-4 col-lg-3">
                <a asp-controller="Invoice" asp-action="Index" class="dash-card">
                    <div class="card text-center h-100">
                        <div class="card-body">
                            <i class="bi bi-receipt fs-3 text-danger"></i>
                            <h6 class="fw-bold mt-2">كل الفواتير</h6>
                            <p>استعراض جميع الفواتير</p>
                        </div>
                    </div>
                </a>
            </div>

            <div class="col-6 col-md-4 col-lg-3">
                <a asp-controller="Invoice" asp-action="Index" asp-route-filter="@SD.hasPoints" class="dash-card">
                    <div class="card text-center h-100">
                        <div class="card-body">
                            <i class="bi bi-check-circle fs-3 text-primary"></i>
                            <h6 class="fw-bold mt-2">تم المراجعة</h6>
                            <p>فواتير بنقاط</p>
                        </div>
                    </div>
                </a>
            </div>

            <div class="col-6 col-md-4 col-lg-3">
                <a asp-controller="Invoice" asp-action="Index" asp-route-filter="@SD.zeroPoints" class="dash-card">
                    <div class="card text-center h-100">
                        <div class="card-body">
                            <i class="bi bi-clock-history fs-3 text-warning"></i>
                            <h6 class="fw-bold mt-2">قيد المراجعة</h6>
                            <p>فواتير بدون نقاط</p>
                        </div>
                    </div>
                </a>
            </div>

            <div class="col-6 col-md-4 col-lg-3">
                <a asp-controller="Customer" asp-action="Customers" class="dash-card">
                    <div class="card text-center h-100">
                        <div class="card-body">
                            <i class="bi bi-people fs-3 text-primary"></i>
                            <h6 class="fw-bold mt-2">العملاء</h6>
                            <p>إدارة حسابات العملاء</p>
                        </div>
                    </div>
                </a>
            </div>

            <div class="col-6 col-md-4 col-lg-3">
                <a href="#" class="dash-card">
                    <div class="card text-center h-100">
                        <div class="card-body">
                            <i class="bi bi-person-badge fs-3 text-success"></i>
                            <h6 class="fw-bold mt-2">الموظفين</h6>
                            <p>إدارة موظفي الفروع</p>
                        </div>
                    </div>
                </a>
            </div>

            <div class="col-6 col-md-4 col-lg-3">
                <a asp-controller="Store" asp-action="Index" class="dash-card">
                    <div class="card text-center h-100">
                        <div class="card-body">
                            <i class="bi bi-shop fs-3 text-secondary"></i>
                            <h6 class="fw-bold mt-2">محلات GLC</h6>
                            <p>عرض الفروع والمحلات</p>
                        </div>
                    </div>
                </a>
            </div>

            <div class="col-6 col-md-4 col-lg-3">
                <a href="#" class="dash-card">
                    <div class="card text-center h-100">
                        <div class="card-body">
                            <i class="bi bi-arrow-repeat fs-3 text-dark"></i>
                            <h6 class="fw-bold mt-2">سنة جديدة</h6>
                            <p>إعادة ضبط النظام السنوي</p>
                        </div>
                    </div>
                </a>
            </div>

        </div>
    }
    else if (User.HasClaim(c => c.Type == SD.Role_Employee))
    {
        <h4 class="fw-bold text-success text-center mb-3">
            <i class="bi bi-person-badge"></i> لوحة تحكم الموظف
        </h4>

        <div class="row g-3   justify-content-center">

            <div class="col-6 col-md-4">
                <a asp-controller="Invoice" asp-action="Index"  class="dash-card">
                    <div class="card text-center h-100">
                        <div class="card-body">
                            <i class="bi bi-shop fs-3 text-success"></i>
                            <h6 class="fw-bold mt-2">فواتير المحل</h6>
                            <p>فواتير الفرع التابع له</p>
                        </div>
                    </div>
                </a>
            </div>

            <div class="col-6 col-md-4">
                <a asp-controller="Invoice" asp-action="Index" asp-route-filter="@SD.zeroPoints" class="dash-card">
                    <div class="card text-center h-100">
                        <div class="card-body">
                            <i class="bi bi-clock fs-3 text-warning"></i>
                            <h6 class="fw-bold mt-2">قيد المراجعة</h6>
                            <p>فواتير تحتاج اعتماد</p>
                        </div>
                    </div>
                </a>
            </div>

            <div class="col-6 col-md-4">
                <a asp-controller="Invoice" asp-action="Index" asp-route-filter="@SD.hasPoints" class="dash-card">
                    <div class="card text-center h-100">
                        <div class="card-body">
                            <i class="bi bi-check-circle fs-3 text-primary"></i>
                            <h6 class="fw-bold mt-2">اعتماد الفواتير</h6>
                            <p>الموافقة على الفواتير</p>
                        </div>
                    </div>
                </a>
            </div>

        </div>
    }
    else if (User.HasClaim(c => c.Type == SD.Role_Client))
    {
        <h4 class="fw-bold text-primary text-center mb-3">
            <i class="bi bi-person"></i> لوحة تحكم العميل
        </h4>

        <div class="row g-3  justify-content-center">

            <div class="col-6 col-md-4">
                <a asp-controller="Invoice" asp-action="create" class="dash-card">
                    <div class="card text-center h-100">
                        <div class="card-body">
                            <i class="bi bi-plus-circle fs-3 text-primary"></i>
                            <h6 class="fw-bold mt-2">إضافة فاتورة</h6>
                            <p>تسجيل فاتورة جديدة</p>
                        </div>
                    </div>
                </a>
            </div>

            <div class="col-6 col-md-4">
                <a asp-controller="customer" asp-action="index" class="dash-card">
                    <div class="card text-center h-100">
                        <div class="card-body">
                            <i class="bi bi-receipt fs-3 text-secondary"></i>
                            <h6 class="fw-bold mt-2">فواتيري</h6>
                            <p>عرض جميع الفواتير</p>
                        </div>
                    </div>
                </a>
            </div>

        </div>
    }
    else 
    {
    
    <div class="row text-center g-4">
        <div class="col-md-3">
            <div class="card shadow-sm border-0 h-100 p-3">
                <div class="card-body">
                    <i class="bi bi-shop fs-1 text-primary mb-3"></i>
                    <h5 class="fw-bold">إدارة المحلات</h5>
                    <p class="text-muted">أضف أو عدّل بيانات المحلات والفروع بسهولة</p>
                </div>
            </div>
        </div>

        <div class="col-md-3">
            <div class="card shadow-sm border-0 h-100 p-3">
                <div class="card-body">
                    <i class="bi bi-receipt fs-1 text-success mb-3"></i>
                    <h5 class="fw-bold">إدارة الفواتير</h5>
                    <p class="text-muted">تابع جميع الفواتير وأضف فواتير جديدة بسرعة</p>
                </div>
            </div>
        </div>

        <div class="col-md-3">
            <div class="card shadow-sm border-0 h-100 p-3">
                <div class="card-body">
                    <i class="bi bi-stars fs-1 text-warning mb-3"></i>
                    <h5 class="fw-bold">النقاط</h5>
                    <p class="text-muted">تتبع النقاط لكل فاتورة وتحكم في المكافآت</p>
                </div>
            </div>
        </div>

        <div class="col-md-3">
            <div class="card shadow-sm border-0 h-100 p-3">
                <div class="card-body">
                    <i class="bi bi-people fs-1 text-danger mb-3"></i>
                    <h5 class="fw-bold">الموظفين والعملاء</h5>
                    <p class="text-muted">إدارة المستخدمين مع التحكم بالصلاحيات بسهولة</p>
                </div>
            </div>
        </div>
    </div>

    }
</div>